"""add email verification fields to users

Revision ID: dfd183441d97
Revises: 036866f6b7ab
Create Date: 2026-05-14 00:51:28.149046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd183441d97'
down_revision: Union[str, None] = '036866f6b7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add email_verified with server_default=false so existing rows get a value,
    # then backfill: anyone who already has an account predates this feature, so
    # mark them as verified to avoid locking them out (admin in particular).
    op.add_column(
        'users',
        sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.execute("UPDATE users SET email_verified = true")
    op.alter_column('users', 'email_verified', server_default=None)

    op.add_column('users', sa.Column('verification_token', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('verification_token_expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_column('users', 'verification_token_expires_at')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
